services:

  playstation2mqtt:
    container_name: playstation2mqtt
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5454:5454
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
