services:

  node-ps5-actor:
    container_name: node-ps5-actor
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5454:5454
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
