services:

  playstation2mqtt:
    container_name: playstation2mqtt
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 4242:4242
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MQTT_BROKER_URL=${MQTT_BROKER_URL}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - SERVER_NAME=${SERVER_NAME}
      - NODE_ID=${NODE_ID}
    volumes:
      - ./credentials.json:/root/.config/playactor/credentials.json
    stdin_open: true
